version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    # ports:
    #   - "9092:9092"
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 #,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c", "sleep 50 && /scripts/create-topics.sh"]
    volumes:
      - ./scripts:/scripts

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
    - mongo_data:/data/db

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - kafka-setup
    environment:
      KAFKA_BROKER: kafka:9092

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    # expose:
    #   - 9092
    depends_on:
      - mongo
      - kafka-setup
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongo:27017

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - consumer
      - producer
    environment:
      FLASK_ENV: development
      MONGO_URI: mongodb://mongo:27017

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
    name: commodities-price-dashboard
