version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 
    depends_on:
      - zookeeper
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
    - mongo_data:/data/db

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongo:27017

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongo:27017

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "6053:6053"
    expose:
      - 6053
    depends_on:
      - mongo
      - consumer
      - producer
    environment:  
      FLASK_ENV: development
      MONGO_URI: mongodb://mongo:27017

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
    name: commodities-price-dashboard